-- 멤버 테이블 --
CREATE TABLE MEMBER(
USER_ID VARCHAR2(20) PRIMARY KEY,
USER_PW VARCHAR2(20) NOT NULL,
USER_NM VARCHAR2(20) NOT NULL,
CAT_NM VARCHAR2(20) DEFAULT '냥이',
EMAIL VARCHAR(30) NOT NULL,
PHONE_NO VARCHAR(30) NOT NULL,
ADDRESS VARCHAR(100) NOT NULL
);


-- 리뷰 테이블 --
CREATE TABLE REVIEW(
R_NO INT PRIMARY KEY,
P_NO INT NOT NULL,
R_WRITER VARCHAR2(20) NOT NULL,
R_CONTENT VARCHAR(1000) NOT NULL,
R_DT DATE NOT NULL,
R_RATE INT NOT NULL
);


-- 오더 테이블 --
CREATE TABLE ORDER_INFO(
O_NO INT PRIMARY KEY,
USER_ID VARCHAR2(20) NOT NULL,
O_DT DATE NOT NULL,
RCV_NM VARCHAR(30) NOT NULL,
RCV_PHONE_NO VARCHAR(30) NOT NULL,
RCV_ADDRESS VARCHAR(100) NOT NULL,
O_PAY VARCHAR(30) NOT NULL
)


-- 오더 디테일 테이블 --
CREATE TABLE ORDER_DETAIL(
OD_NO INT PRIMARY KEY,
O_NO INT NOT NULL,
P_NO INT NOT NULL,
OD_CNT INT NOT NULL
);


 
— 프로덕트 테이블 — 
CREATE TABLE PRODUCT(
P_NO INT PRIMARY KEY,
P_NM VARCHAR(200) NOT NULL,  --크롤링
CATEGORY VARCHAR(20) NOT NULL,  
PRICE INT NOT NULL,  -- 크롤링
P_AMT INT NOT NULL,
P_DETAIL VARCHAR(2000) NOT NULL,  -- 크롤링
P_IMG_URL VARCHAR(200) NOT NULL,  -- 크롤링
P_IMG_URL2 VARCHAR(200) NOT NULL,  -- 크롤링
DC_PERCENT INT DEFAULT 0
);


-- 프로덕트 시퀀스 --
CREATE SEQUENCE PRODUCT_SEQ
       INCREMENT BY 1
       START WITH 1
       MINVALUE 1
       MAXVALUE 9999
       NOCYCLE
       NOCACHE
       NOORDER;
       

-- 리뷰 테이블 시퀀스 —-
CREATE SEQUENCE REVIEW_SEQ
       INCREMENT BY 1
       START WITH 1
       MINVALUE 1
       MAXVALUE 9999
       NOCYCLE
       NOCACHE
       NOORDER;
       
       
-- 오더 테이블 시퀀스 --
CREATE SEQUENCE ORDER_SEQ
       INCREMENT BY 1
       START WITH 1
       MINVALUE 1
       MAXVALUE 9999
       NOCYCLE
       NOCACHE
       NOORDER;
      
      
-- 오더 디테일 테이블 시퀀스 —-
CREATE SEQUENCE ORDER_DETAIL_SEQ
       INCREMENT BY 1
       START WITH 1
       MINVALUE 1
       MAXVALUE 9999
       NOCYCLE
       NOCACHE
       NOORDER;
