SELECT * FROM USER_TABLES;

SELECT * FROM MEMBER;

SELECT * FROM PRODUCT;

SELECT * FROM ORDER_INFO;

SELECT * FROM ORDER_DETAIL;

SELECT * FROM PRODUCT ORDER BY P_NO ASC;

SELECT * FROM (SELECT * FROM PRODUCT ORDER BY P_NO DESC) WHERE ROWNUM<=10

SELECT PRODUCT.P_NO,P_NM,PRICE,P_IMG_URL,CATEGORY, SUM(OD_CNT), DC_PERCENT,P_AMT,P_DETAIL,P_IMG_URL2  
FROM PRODUCT INNER JOIN ORDER_DETAIL ON ORDER_DETAIL.P_NO = PRODUCT.P_NO 
GROUP BY PRODUCT.P_NO,P_NM,PRICE,P_IMG_URL,CATEGORY,DC_PERCENT,P_AMT,P_DETAIL ,P_IMG_URL2 ORDER BY SUM(OD_CNT) DESC;		 

SELECT * FROM ORDER_DETAIL;

SELECT * FROM PRODUCT ORDER BY PRICE*(100-DC_PERCENT) DESC;

SELECT P_NO, CATEGORY, P_NM, PRICE, P_IMG_URL, DC_PERCENT, PRICE*(100-DC_PERCENT)*100 AS DC_PRICE FROM PRODUCT ORDER BY DC_PRICE DESC;

SELECT ORDER_INFO.O_DT, SUM(PRODUCT.PRICE*((100-PRODUCT.DC_PERCENT)/100)*ORDER_DETAIL.OD_CNT) AS TOTAL
FROM ORDER_DETAIL, PRODUCT, ORDER_INFO WHERE ORDER_DETAIL.P_NO = PRODUCT.P_NO AND ORDER_DETAIL.O_NO = ORDER_INFO.O_NO AND ORDER_INFO.O_DT
BETWEEN TO_DATE('20230101', 'YYYYMMDD') AND TO_DATE('20231231') GROUP BY ORDER_DETAIL.O_NO, ORDER_INFO.O_DT ORDER BY ORDER_INFO.O_DT DESC;




-- 드랍 테이블 --
DROP TABLE MEMBER;

DROP TABLE PRODUCT;

DROP TABLE REVIEW;

DROP TABLE ORDER_INFO;

DROP TABLE ORDER_DETAIL;




-- 드랍 테이블 시퀀스 --
DROP SEQUENCE PRODUCT_SEQ;
  
DROP SEQUENCE REVIEW_SEQ;

DROP SEQUENCE ORDER_SEQ;
  
DROP SEQUENCE ORDER_DETAIL_SEQ;